name: Prime Number Workflow

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@main

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build -c Release

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack -c Release

    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/welton-andrade/index.json -n github -u welton-andrade -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Push Package on GitHub Packages
      # run: dotnet nuget push "PrimeNumber/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} --source "github"
      # run: dotnet nuget push "PrimeNumber/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/welton-andrade/index.json"
      # run: dotnet nuget push "PrimeNumber/bin/Release/*.nupkg" --source "github" --api-key API_KEY
      # run: dotnet nuget push "PrimeNumber/bin/Release/*.nupkg" -s github -k NUGET_TOKEN
      run: dotnet nuget push bin/Release/*.nupkg --s "github"
      env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
